# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_basic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import qdarktheme

from poker_game import game


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Add poker table to screen

        self.Table = QtWidgets.QLabel(self.centralwidget)
        self.Table.setGeometry(QtCore.QRect(60, 90, 821, 381))
        self.Table.setText("")
        self.Table.setPixmap(QtGui.QPixmap("../Project/Images/table.webp"))
        self.Table.setScaledContents(True)
        self.Table.setObjectName("Table")

        # Create poker card images
        cards = []
        for player in game.players:
            for card in player.hand.cards:
                cards.append(f"{card.rank}_of_{card.suit}")

        # Show user cards

        self.p1_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p1_c1.setGeometry(QtCore.QRect(390, 420, 71, 101))
        self.p1_c1.setText("")
        self.p1_c1.setPixmap(QtGui.QPixmap(
            f"images/cards/{cards[0]}"))
        self.p1_c1.setScaledContents(True)
        self.p1_c1.setObjectName("p1_c1")
        self.p1_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p1_c2.setGeometry(QtCore.QRect(470, 420, 71, 101))
        self.p1_c2.setText("")
        self.p1_c2.setPixmap(QtGui.QPixmap(
            f"images/cards/{cards[1]}"))
        self.p1_c2.setScaledContents(True)
        self.p1_c2.setObjectName("p1_c2")

        self.p2_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p2_c1.setGeometry(QtCore.QRect(790, 410, 71, 101))
        self.p2_c1.setText("")
        self.p2_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p2_c1.setScaledContents(True)
        self.p2_c1.setObjectName("p2_c1")
        self.p2_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p2_c2.setGeometry(QtCore.QRect(710, 410, 71, 101))
        self.p2_c2.setText("")
        self.p2_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p2_c2.setScaledContents(True)
        self.p2_c2.setObjectName("p2_c2")
        self.p3_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p3_c1.setGeometry(QtCore.QRect(190, 420, 71, 101))
        self.p3_c1.setText("")
        self.p3_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p3_c1.setScaledContents(True)
        self.p3_c1.setObjectName("p3_c1")
        self.p3_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p3_c2.setGeometry(QtCore.QRect(110, 420, 71, 101))
        self.p3_c2.setText("")
        self.p3_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p3_c2.setScaledContents(True)
        self.p3_c2.setObjectName("p3_c2")
        self.p4_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p4_c1.setGeometry(QtCore.QRect(40, 100, 71, 101))
        self.p4_c1.setText("")
        self.p4_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p4_c1.setScaledContents(True)
        self.p4_c1.setObjectName("p4_c1")
        self.p4_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p4_c2.setGeometry(QtCore.QRect(120, 100, 71, 101))
        self.p4_c2.setText("")
        self.p4_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p4_c2.setScaledContents(True)
        self.p4_c2.setObjectName("p4_c2")
        self.p5_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p5_c1.setGeometry(QtCore.QRect(390, 40, 71, 101))
        self.p5_c1.setText("")
        self.p5_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p5_c1.setScaledContents(True)
        self.p5_c1.setObjectName("p5_c1")
        self.p5_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p5_c2.setGeometry(QtCore.QRect(470, 40, 71, 101))
        self.p5_c2.setText("")
        self.p5_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p5_c2.setScaledContents(True)
        self.p5_c2.setObjectName("p5_c2")
        self.p6_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p6_c1.setGeometry(QtCore.QRect(750, 90, 71, 101))
        self.p6_c1.setText("")
        self.p6_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p6_c1.setScaledContents(True)
        self.p6_c1.setObjectName("p6_c1")
        self.p6_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p6_c2.setGeometry(QtCore.QRect(830, 90, 71, 101))
        self.p6_c2.setText("")
        self.p6_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p6_c2.setScaledContents(True)
        self.p6_c2.setObjectName("p6_c2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 540, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 580, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 580, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 540, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Table.raise_()
        self.p2_c1.raise_()
        self.p2_c2.raise_()
        self.p3_c1.raise_()
        self.p3_c2.raise_()
        self.p4_c1.raise_()
        self.p4_c2.raise_()
        self.p5_c1.raise_()
        self.p5_c2.raise_()
        self.p6_c1.raise_()
        self.p6_c2.raise_()
        self.p1_c2.raise_()
        self.p1_c1.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Check"))
        self.pushButton_2.setText(_translate("MainWindow", "Raise"))
        self.pushButton_3.setText(_translate("MainWindow", "Fold"))
        self.pushButton_4.setText(_translate("MainWindow", "Call"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qdarktheme.setup_theme()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
