# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3rd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import qdarktheme


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 670)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Add poker table to screen

        self.Table = QtWidgets.QLabel(self.centralwidget)
        self.Table.setGeometry(QtCore.QRect(60, 90, 821, 381))
        self.Table.setText("")
        self.Table.setPixmap(QtGui.QPixmap("../Project/Images/table.webp"))
        self.Table.setScaledContents(True)
        self.Table.setObjectName("Table")

        # self.displayBlinds()

    # Show user cards

        self.p1_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p1_c1.setGeometry(QtCore.QRect(390, 410, 71, 101))
        self.p1_c1.setText("")
        self.p1_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p1_c1.setScaledContents(True)
        self.p1_c1.setObjectName("p1_c1")
        self.p1_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p1_c2.setGeometry(QtCore.QRect(470, 410, 71, 101))
        self.p1_c2.setText("")
        self.p1_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p1_c2.setScaledContents(True)
        self.p1_c2.setObjectName("p1_c2")

        self.p2_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p2_c1.setGeometry(QtCore.QRect(70, 400, 71, 101))
        self.p2_c1.setText("")
        self.p2_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p2_c1.setScaledContents(True)
        self.p2_c1.setObjectName("p2_c1")
        self.p2_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p2_c2.setGeometry(QtCore.QRect(150, 400, 71, 101))
        self.p2_c2.setText("")
        self.p2_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p2_c2.setScaledContents(True)
        self.p2_c2.setObjectName("p2_c2")

        self.p3_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p3_c1.setGeometry(QtCore.QRect(30, 90, 71, 101))
        self.p3_c1.setText("")
        self.p3_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p3_c1.setScaledContents(True)
        self.p3_c1.setObjectName("p3_c1")
        self.p3_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p3_c2.setGeometry(QtCore.QRect(110, 90, 71, 101))
        self.p3_c2.setText("")
        self.p3_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p3_c2.setScaledContents(True)
        self.p3_c2.setObjectName("p3_c2")

        self.p4_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p4_c1.setGeometry(QtCore.QRect(390, 30, 71, 101))
        self.p4_c1.setText("")
        self.p4_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p4_c1.setScaledContents(True)
        self.p4_c1.setObjectName("p4_c1")
        self.p4_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p4_c2.setGeometry(QtCore.QRect(470, 30, 71, 101))
        self.p4_c2.setText("")
        self.p4_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p4_c2.setScaledContents(True)
        self.p4_c2.setObjectName("p4_c2")

        self.p5_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p5_c1.setGeometry(QtCore.QRect(720, 50, 71, 101))
        self.p5_c1.setText("")
        self.p5_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p5_c1.setScaledContents(True)
        self.p5_c1.setObjectName("p5_c1")
        self.p5_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p5_c2.setGeometry(QtCore.QRect(800, 50, 71, 101))
        self.p5_c2.setText("")
        self.p5_c2.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p5_c2.setScaledContents(True)
        self.p5_c2.setObjectName("p5_c2")

        self.p6_c1 = QtWidgets.QLabel(self.centralwidget)
        self.p6_c1.setGeometry(QtCore.QRect(690, 420, 71, 101))
        self.p6_c1.setText("")
        self.p6_c1.setPixmap(QtGui.QPixmap(
            "images/cards/back.jpg"))
        self.p6_c1.setScaledContents(True)
        self.p6_c1.setObjectName("p6_c1")
        self.p6_c2 = QtWidgets.QLabel(self.centralwidget)
        self.p6_c2.setGeometry(QtCore.QRect(770, 420, 71, 101))
        self.p6_c2.setAutoFillBackground(True)
        self.p6_c2.setText("")
        self.p6_c2.setPixmap(QtGui.QPixmap("images/cards/back.jpg"))
        self.p6_c2.setScaledContents(True)
        self.p6_c2.setWordWrap(False)
        self.p6_c2.setOpenExternalLinks(False)
        self.p6_c2.setObjectName("p6_c2")

        # Set up player buttons
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 560, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 560, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 590, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 590, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")

        # Set up board cards (cards on the table)
        self.B1 = QtWidgets.QLabel(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(270, 220, 71, 101))
        self.B1.setText("")
        self.B1.setPixmap(QtGui.QPixmap(
            ""))
        self.B1.setScaledContents(True)
        self.B1.setObjectName("B1")
        self.B2 = QtWidgets.QLabel(self.centralwidget)
        self.B2.setGeometry(QtCore.QRect(350, 220, 71, 101))
        self.B2.setText("")
        self.B2.setPixmap(QtGui.QPixmap(
            ""))
        self.B2.setScaledContents(True)
        self.B2.setObjectName("B2")
        self.B3 = QtWidgets.QLabel(self.centralwidget)
        self.B3.setGeometry(QtCore.QRect(430, 220, 71, 101))
        self.B3.setText("")
        self.B3.setPixmap(QtGui.QPixmap(
            ""))
        self.B3.setScaledContents(True)
        self.B3.setObjectName("B3")
        self.B4 = QtWidgets.QLabel(self.centralwidget)
        self.B4.setGeometry(QtCore.QRect(510, 220, 71, 101))
        self.B4.setText("")
        self.B4.setPixmap(QtGui.QPixmap(
            ""))
        self.B4.setScaledContents(True)
        self.B4.setObjectName("B4")
        self.B5 = QtWidgets.QLabel(self.centralwidget)
        self.B5.setGeometry(QtCore.QRect(590, 220, 71, 101))
        self.B5.setText("")
        self.B5.setPixmap(QtGui.QPixmap(
            ""))
        self.B5.setScaledContents(True)
        self.B5.setObjectName("B5")

        # Set up player names labels
        self.p1_name = QtWidgets.QLabel(self.centralwidget)
        self.p1_name.setGeometry(QtCore.QRect(380, 520, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p1_name.setFont(font)
        self.p1_name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p1_name.setScaledContents(True)
        self.p1_name.setWordWrap(False)
        self.p1_name.setObjectName("p1_name")
        self.p2_name = QtWidgets.QLabel(self.centralwidget)
        self.p2_name.setGeometry(QtCore.QRect(60, 510, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p2_name.setFont(font)
        self.p2_name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p2_name.setScaledContents(True)
        self.p2_name.setWordWrap(False)
        self.p2_name.setObjectName("p2_name")
        self.p3_name = QtWidgets.QLabel(self.centralwidget)
        self.p3_name.setGeometry(QtCore.QRect(20, 50, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p3_name.setFont(font)
        self.p3_name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p3_name.setScaledContents(True)
        self.p3_name.setWordWrap(False)
        self.p3_name.setObjectName("p3_name")
        self.p4_name = QtWidgets.QLabel(self.centralwidget)
        self.p4_name.setGeometry(QtCore.QRect(380, 0, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p4_name.setFont(font)
        self.p4_name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p4_name.setScaledContents(True)
        self.p4_name.setWordWrap(False)
        self.p4_name.setObjectName("p4_name")
        self.p5_name = QtWidgets.QLabel(self.centralwidget)
        self.p5_name.setGeometry(QtCore.QRect(710, 20, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p5_name.setFont(font)
        self.p5_name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p5_name.setScaledContents(True)
        self.p5_name.setWordWrap(False)
        self.p5_name.setObjectName("p5_name")
        self.p6_name = QtWidgets.QLabel(self.centralwidget)
        self.p6_name.setGeometry(QtCore.QRect(680, 520, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p6_name.setFont(font)
        self.p6_name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p6_name.setScaledContents(True)
        self.p6_name.setWordWrap(False)
        self.p6_name.setObjectName("p6_name")

        # Set up player chips labels

        self.p1_chips = QtWidgets.QLabel(self.centralwidget)
        self.p1_chips.setGeometry(QtCore.QRect(470, 520, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.p1_chips.setFont(font)
        self.p1_chips.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p1_chips.setScaledContents(True)
        self.p1_chips.setWordWrap(False)
        self.p1_chips.setObjectName("p1_chips")
        self.p2_chips = QtWidgets.QLabel(self.centralwidget)
        self.p2_chips.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.p2_chips.setFont(font)
        self.p2_chips.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p2_chips.setScaledContents(True)
        self.p2_chips.setWordWrap(False)
        self.p2_chips.setObjectName("p2_chips")
        self.p3_chips = QtWidgets.QLabel(self.centralwidget)
        self.p3_chips.setGeometry(QtCore.QRect(110, 50, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.p3_chips.setFont(font)
        self.p3_chips.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p3_chips.setScaledContents(True)
        self.p3_chips.setWordWrap(False)
        self.p3_chips.setObjectName("p3_chips")
        self.p4_chips = QtWidgets.QLabel(self.centralwidget)
        self.p4_chips.setGeometry(QtCore.QRect(470, 0, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.p4_chips.setFont(font)
        self.p4_chips.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p4_chips.setScaledContents(True)
        self.p4_chips.setWordWrap(False)
        self.p4_chips.setObjectName("p4_chips")
        self.p5_chips = QtWidgets.QLabel(self.centralwidget)
        self.p5_chips.setGeometry(QtCore.QRect(800, 20, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.p5_chips.setFont(font)
        self.p5_chips.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p5_chips.setScaledContents(True)
        self.p5_chips.setWordWrap(False)
        self.p5_chips.setObjectName("p5_chips")
        self.p6_chips = QtWidgets.QLabel(self.centralwidget)
        self.p6_chips.setGeometry(QtCore.QRect(770, 520, 81, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.p6_chips.setFont(font)
        self.p6_chips.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.p6_chips.setScaledContents(True)
        self.p6_chips.setWordWrap(False)
        self.p6_chips.setObjectName("p6_chips")

        # HANDLE BLINDS TEMPORARILY

        # Creating the QLabel for the big blind label
        self.big_blind_label = QtWidgets.QLabel(self.centralwidget)

        # Set the geometry of the big blind label based on the position of the player
        self.big_blind_label.setGeometry(QtCore.QRect(
            0, 0, 30, 30))
        # The position of the big blind label is slightly shifted to stand out
        self.big_blind_label.setStyleSheet(
            "background-color: red; border-radius: 15px; color: white;")
        self.big_blind_label.setText("BB")
        self.big_blind_label.setAlignment(QtCore.Qt.AlignCenter)
        self.big_blind_label.show()

        self.small_blind_label = QtWidgets.QLabel(self.centralwidget)

        # Set the geometry of the small blind label based on the position of the player
        self.small_blind_label.setGeometry(QtCore.QRect(
            0, 0, 30, 30))
        # The position of the small blind label is slightly shifted to stand out
        self.small_blind_label.setStyleSheet(
            "background-color: yellow; border-radius: 15px; color: red;")
        self.small_blind_label.setText("SB")
        self.small_blind_label.setAlignment(QtCore.Qt.AlignCenter)
        self.small_blind_label.show()

        self.dealer_button_label = QtWidgets.QLabel(self.centralwidget)
        self.dealer_button_label.setGeometry(QtCore.QRect(
            0, 0, 30, 30))
        self.dealer_button_label.setStyleSheet(
            "background-color: white; border-radius: 15px; color: black;")
        self.dealer_button_label.setText("D")
        self.dealer_button_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dealer_button_label.show()

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Call"))
        self.pushButton.setText(_translate("MainWindow", "Check"))
        self.pushButton_2.setText(_translate("MainWindow", "Raise"))
        self.pushButton_3.setText(_translate("MainWindow", "Fold"))
        self.p1_name.setText(_translate("MainWindow", "PlayerName"))
        self.p2_name.setText(_translate("MainWindow", "PlayerName"))
        self.p3_name.setText(_translate("MainWindow", "PlayerName"))
        self.p4_name.setText(_translate("MainWindow", "PlayerName"))
        self.p5_name.setText(_translate("MainWindow", "PlayerName"))
        self.p6_name.setText(_translate("MainWindow", "PlayerName"))
        self.p1_chips.setText(_translate("MainWindow", "Chips: 1000"))
        self.p2_chips.setText(_translate("MainWindow", "Chips: 1000"))
        self.p3_chips.setText(_translate("MainWindow", "Chips: 1000"))
        self.p4_chips.setText(_translate("MainWindow", "Chips: 1000"))
        self.p5_chips.setText(_translate("MainWindow", "Chips: 1000"))
        self.p6_chips.setText(_translate("MainWindow", "Chips: 1000"))

    def displayNames(self, names):
        self.p1_name.setText(f"{names[0]}")
        self.p2_name.setText(f"{names[1]}")
        self.p3_name.setText(f"{names[2]}")
        self.p4_name.setText(f"{names[3]}")
        self.p5_name.setText(f"{names[4]}")
        self.p6_name.setText(f"{names[5]}")

    def displayChips(self, chips):
        self.p1_chips.setText(f"Chips: {chips[0]}")
        self.p2_chips.setText(f"Chips: {chips[1]}")
        self.p3_chips.setText(f"Chips: {chips[2]}")
        self.p4_chips.setText(f"Chips: {chips[3]}")
        self.p5_chips.setText(f"Chips: {chips[4]}")
        self.p6_chips.setText(f"Chips: {chips[5]}")

    def displayBlinds(self, big_blind_player_index, small_blind_player_index, dealer_button_player_index):
        # These are the positions of the first card of each player
        player_positions = [(390, 410), (70, 400), (30, 90),
                            (390, 30), (720, 50), (690, 420)]

        # Set the geometry of the big blind label based on the position of the player
        big_blind_current_player_pos = player_positions[big_blind_player_index]
        self.big_blind_label.setGeometry(QtCore.QRect(
            big_blind_current_player_pos[0] - 30, big_blind_current_player_pos[1], 30, 30))
        # self.big_blind_label.show()

        # Set the geometry of the small blind label based on the position of the player
        small_blind_player_pos = player_positions[small_blind_player_index]
        self.small_blind_label.setGeometry(QtCore.QRect(
            small_blind_player_pos[0] - 30, small_blind_player_pos[1], 30, 30))
        # self.small_blind_label.show()

        dealer_button_player_pos = player_positions[dealer_button_player_index]
        self.dealer_button_label.setGeometry(QtCore.QRect(
            dealer_button_player_pos[0] - 30, dealer_button_player_pos[1], 30, 30))
        # self.dealer_button_label.show()

    def displayCards(self, cards):
        self.p1_c1.setPixmap(QtGui.QPixmap(
            f"images/cards/{cards[0]}"))
        self.p1_c2.setPixmap(QtGui.QPixmap(
            f"images/cards/{cards[1]}"))

    def displayBoard(self, board):
        self.B1.setPixmap(QtGui.QPixmap(
            f"images/cards/{board[0]}"))
        self.B2.setPixmap(QtGui.QPixmap(
            f"images/cards/{board[1]}"))
        self.B3.setPixmap(QtGui.QPixmap(
            f"images/cards/{board[2]}"))
        if len(board) == 4:
            self.B4.setPixmap(QtGui.QPixmap(
                f"images/cards/{board[3]}"))
        elif len(board) == 5:
            self.B5.setPixmap(QtGui.QPixmap(
                f"images/cards/{board[4]}"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    qdarktheme.setup_theme()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
